game:
  prefix: "[TheJourney]"
  universe: "SKY_LAND"
  messages:
    complete-quest: "You finish quest <QUEST_NAME>."
    complete-bonus: "You finish the bonus quest <QUEST_NAME>."
    quests-count: "Quests finished on this universe <DONE>/<COUNT>."
    all-completed: "You complete all quests on this universe, you can go to the next universe."
    universe-switch-warning: "§cBe careful you will lost all your inventory, only enderchest is saved."
    player-not-found: "§cCan't found this player."
    no-perms: "§cYou don't have permission to do that."
  main-gui:
    size: 27
    title: "The Sky lands"
    info:
      name: "Universe: Sky lands"
      lore: ["Overview:", "Overworld, Nether, End", "14 quests, 1 bonus slot"]
    stats:
      name: "Your stats"
      lore: ["Quests done: <FINISHED_QUESTS>", "Bonus slots: <BONUS>", "Total done: <TOTAL>"]
    quests:
      name: "Current quests"
      lore: ["Click to see", "all the quests", "from this universe"]
  quests-gui:
    size: 27
    title: "Quests"
    no-quest: " "
    locked: "Quest locked"
  journey-chest:
    size: 9
    title: "Journey Chest"
    base-slots: 3
    locked: "§cSlot locked"
  switch-gui:
    size: 27
    title: "Universe switch"
    lore: ["Go to the next","universe: <NEXT>"]
    accept:
      name: "Let's go"
      lore: ["You will lost", "your inventory", "only journey chest", "will follow you"]
    deny:
      name: "I'm not ready"
      lore: ["I prefer stay", "here to organize", "my journey chest"]
#

data:
  event-name: "The Journey"
  mongo:
    databases: ["master", "event_journey"]
    host: "127.0.0.1"
    port: 27017
    user: "minecraft"
    password: "admin"
    db: "admin"
#