game:
  universe: "SKY_LAND"
#

data:
  event-name: "The Journey"
  mongo:
    databases: ["master", "event_journey"]
    host: "127.0.0.1"
    port: 27017
    user: "minecraft"
    password: "admin"
    db: "admin"
#