name: TheJourneyGame
main: fr.grimtown.journey.GamePlugin
version: 1.0
api-version: 1.17
depend:
  - ProtocolLib
description: 'Game plugin for The Journey event, event from Cap sur Grimtown !'
authors:
  - MileKat (tutur1004#8766)
  - BakaAless (Aless#6161)
libraries:
  - org.mongodb:mongodb-driver-sync:4.3.2
  - dev.morphia.morphia:morphia-core:2.2.2
commands:
  journey:
    usage: /journey
    description: "Open main gui"
    aliases: j
  quest:
    usage: /quest
    description: "Open quest gui"
    aliases: q
  chest:
    usage: /chest
    description: "Open journey chest"
    aliases: c
  manage:
    usage: /manage
    description: "Manage quests"
    permission: "mods.quest.manage"
    aliases: mq